### ISSUE TITLE
 Cannot locate rosdep definition for [speed_limit]

### ISSUE THREAD

**Issue by weiqi-chen** [pal-robotics/pmb2_robot#1]
Hello,

Thank for your amazing work.

 I tried to `rosdep`  according to http://wiki.ros.org/Robots/PMB-2 , and ran into error:

rosdep install --from-paths src --ignore-src --rosdistro indigolERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pmb2_bringup: Cannot locate rosdep definition for [speed_limit]

And I can't find which ROS package provide `speed_limit`.

Could you help me out?

Best Regards,
Weiqi Chen.

**Comment by jordi-pages** [comment]
Dear @WeiqiChenCN,

thanks for your feedback. Important changes have been done recently in PAL Robotics' github in order to release the new version of [TIAGo public simulation](http://wiki.ros.org/Robots/TIAGo/), which comes with a comprehensive list of [tutorials](http://wiki.ros.org/Robots/TIAGo/Tutorials). As TIAGo is modular and uses the PMB-2 the public simulation of the latter has also been updated.

We have modified the instructions in http://wiki.ros.org/Robots/PMB-2 so that now you can install it properly.

Best regards

**Comment by weiqi-chen** [comment]
Oh, Thank you.

Best Regards.
